-- MySQL Script generated by MySQL Workbench
-- Wed Dec  8 09:38:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sport` (
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gym` (
  `name` VARCHAR(45) NOT NULL,
  `owner` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` INT NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  INDEX `owner_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `gym` VARCHAR(45) NOT NULL,
  `review` VARCHAR(450) NOT NULL,
  `writer` VARCHAR(45) NULL,
  UNIQUE INDEX `writer_UNIQUE` (`writer` ASC) INVISIBLE,
  UNIQUE INDEX `gym_UNIQUE` (`gym` ASC) VISIBLE,
  PRIMARY KEY (`review`, `gym`),
  CONSTRAINT `gym`
    FOREIGN KEY (`gym`)
    REFERENCES `mydb`.`gym` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `writer`
    FOREIGN KEY (`writer`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `sport` VARCHAR(45) NOT NULL,
  `gym` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NULL,
  PRIMARY KEY (`sport`, `gym`),
  INDEX `gym_idx` (`gym` ASC) VISIBLE,
  CONSTRAINT `sport`
    FOREIGN KEY (`sport`)
    REFERENCES `mydb`.`sport` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gym`
    FOREIGN KEY (`gym`)
    REFERENCES `mydb`.`gym` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'StitchMl' IDENTIFIED BY 'w47730t461014';

GRANT EXECUTE ON ROUTINE `mydb`.* TO 'StitchMl';
GRANT ALL ON `mydb`.* TO 'StitchMl';
GRANT SELECT ON TABLE `mydb`.* TO 'StitchMl';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'StitchMl';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'StitchMl';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
