module sportify {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.base;
    requires javafx.graphics;
    requires java.desktop;
    requires java.sql;
    requires com.sothawo.mapjfx;
    requires javafx.web;
    requires org.apache.commons.lang3;
    requires org.json;
    requires json.simple;
    requires mysql.connector.java;
    requires commons.validator;

    opens it.uniroma2.dicii.ispw.sportify to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify;
    exports it.uniroma2.dicii.ispw.sportify.controller;
    opens it.uniroma2.dicii.ispw.sportify.controller to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.auth;
    opens it.uniroma2.dicii.ispw.sportify.auth to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.controller.graphic;
    opens it.uniroma2.dicii.ispw.sportify.controller.graphic to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.bean;
    opens it.uniroma2.dicii.ispw.sportify.bean to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.controller.graphic.phone;
    opens it.uniroma2.dicii.ispw.sportify.controller.graphic.phone to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.controller.graphic.desktop;
    opens it.uniroma2.dicii.ispw.sportify.controller.graphic.desktop to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.errorlogic;
    opens it.uniroma2.dicii.ispw.sportify.errorlogic to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.util;
    opens it.uniroma2.dicii.ispw.sportify.util to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.model.dao;
    opens it.uniroma2.dicii.ispw.sportify.model.dao to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.model.domain;
    opens it.uniroma2.dicii.ispw.sportify.model.domain to javafx.fxml, javafx.graphics;
    exports it.uniroma2.dicii.ispw.sportify.pattern;
    opens it.uniroma2.dicii.ispw.sportify.pattern to javafx.fxml, javafx.graphics;
}