/*
-- Query: 
-- Date: 2022-02-07 10:28
*/
private static final String INDOOR = 'indoor';
private static final String OUTDOOR = 'outdoor';

INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Volleyball',INDOOR,'pallavolo Sport, chiamato anche volley, che si svolge tra due squadre di 6 giocatori ciascuna. Lo scopo del gioco è realizzare punti facendo cadere la palla nel campo avversario (fase di attacco), impedendo che la squadra avversaria faccia altrettanto (fase difensiva).');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Dance',INDOOR,'La danza è una disciplina e anche uno sport che si esprime nel movimento secondo un piano prestabilito, detto coreografia, o attraverso improvvisazione. È presente in tutte le culture umane. Nella cultura occidentale è documentata fin dalla più profonda preistoria insieme ad altre arti quali il teatro e la musica vocale e/o strumentale. Spesso è accompagnata da musiche o composizioni sonore. La danza nel linguaggio e nella tradizione della danza popolare può essere chiamata anche danza etnica.');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Swimming',INDOOR,'Il nuoto è una attività individuale che permette il galleggiamento e il moto del proprio corpo in acqua. Il nuoto coinvolge quasi tutti i muscoli del corpo. Oltre a essere uno sport olimpico è una attività ricreativa.');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Football',OUTDOOR,'Il calcio è uno sport di squadra giocato  con un pallone su un campo di gioco rettangolare, con due porte. È giocato da due squadre composte da 11 giocatori (sono possibili sostituzioni per infortuni o ragioni tattiche). Dieci di essi possono toccare il pallone solo con i piedi, il corpo e la testa; uno solo posto a difesa della porta (e perciò detto "portiere"), può toccare il pallone anche con mani e braccia, solamente se il pallone si trova in area di rigore. Lo scopo del gioco è quello di segnare più punti (detti gol o reti) della squadra avversaria, facendo passare il pallone oltre la linea della porta avversaria. La durata di una partita è di 90 minuti, divisi in due tempi da 45 ciascuno più un eventuale recupero (a discrezione del Direttore di Gara).');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Trekking',OUTDOOR,'Significato di trekking: lunghe e lente camminate in mezzo alla natura, da soli o in gruppo. Il significato di trekking deve essere ricercato nel verbo inglese to trek, che significa fare un viaggio lungo, camminando piano. Un mix tra camminata in mezzo alla natura ed escursionismo.');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Athletics',OUTDOOR,'Atletica leggera è un insieme di discipline sportive che possono essere sommariamente suddivise in: corse su pista, concorsi (lanci, salti in elevazione e salti in estensione), prove multiple, corse su strada, marcia, corsa campestre e corsa in montagna. Gli eventi di atletica leggera vengono solitamente organizzati attorno a una pista ad anello della lunghezza di 400 m, sulla quale si svolgono le gare di corsa. Le gare di lanci e salti, invece, si svolgono sul campo racchiuso dalla pista.');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Tennis',OUTDOOR,'Il tennis (il nome può essere tradotto in italiano con un termine arcaico non più in uso quale “schiaffo palla”) è uno sport della racchetta che vede opposti due o quattro giocatori (due contro due, incontro di doppio) in un campo da gioco diviso in due metà da una rete alta 0,914 m al centro e 1,07 m ai lati.');
INSERT INTO `sport` (`name`,`type`,`description`) VALUES ('Golf',OUTDOOR,'Il golf è uno sport di precisione che si pratica in un campo aperto (coltivato a prato) appositamente attrezzato, per mezzo di una palla e una serie di ferri e legni. Sebbene da alcuni sia ritenuto uno sport di origine olandese, il paese in cui godette per primo di enorme popolarità e grande tradizione fu la Scozia (in cui è gioco nazionale).');
